---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2023 The Nephio Authors.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

reconcile_timeout: 10m
nephio_catalog_repo_uri: https://github.com/vitu1234/catalog.git
nephio_catalog_branch: main
k8s:
  context: kubernetes
  version: v1.29.2