- hosts: localhost
  gather_facts: true
  vars_files:
        - cred.yml
  tasks:
    - name: Running Main OpenStack Role
      include_role:
        name: openstack-main


- hosts: openstack_control
  gather_facts: true
  vars_files:
    - cred.yml
  tasks:
    - name: Running K8s Control Role
      include_role:
        name: k8s_control

- hosts: openstack_worker
  gather_facts: true
  tasks:
    - name: Running K8s Worker Role
      include_role:
        name: k8s_workernode

- hosts: openstack_control
  gather_facts: true
  vars_files:
    - cred.yml
  environment:
    AWS_REGION: ap-northeast-2
    AWS_ACCESS_KEY_ID: ""
    AWS_SECRET_ACCESS_KEY: ""
    AWS_SESSION_TOKEN: 
  tasks:
    - name: Running CAPO Role
      include_role:
        name: capo

- hosts: openstack_control
  gather_facts: true
  vars_files:
     - mgmt.yml
  tasks:
    - name: Running K8s Control Nephio Bootstrap
      ansible.builtin.include_tasks: cluster.yml